PN-4505 890: RECAG012 e RECAG011B
pagopa/pn-paper-channel pull request #219
Opened 2023-03-13 18:12 UTC by vincenzo-racca-pa

2023-03-15 13:07 UTC, fabriziolana requested changes

2023-03-15 13:07 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/RECAG012MessageHandler.java
> +// Il RECAG012 è considerato come entità logica un metadata
scriverei un pò più nel dettaglio cosa deve fare questa classe, "in accordo con le specifiche" non aiuta per niente a capire che vuol dire :)

2023-03-15 13:07 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/RECAG011BMessageHandler.java
> +public class RECAG011BMessageHandler extends SaveDematMessageHandler {
scrivere l'algoritmo da qualche parte come commento

2023-03-15 13:48 UTC, fabriziolana submitted a review, later dismissed

2023-03-16 09:28 UTC, fabriziolana submitted a review, later dismissed

2023-03-16 14:37 UTC, fabriziolana approved these changes

2023-03-30 14:43 UTC, fabriziolana approved these changes

2023-04-05 14:22 UTC, federicofatica-pagopa approved these changes

2023-04-05 14:34 UTC, merged