Feature/pn 4504
pagopa/pn-paper-channel pull request #221
Opened 2023-03-14 11:26 UTC by FeliceMente

c'è sia lo unit test che l'integration test per la gestione eventi finali

2023-03-14 15:54 UTC, fabriziolana requested changes

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +                .block();
non c'è motivo di usare block, tutta la catena deve tornare un Mono<Void>

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +        if (missingMeta.get()) {
questo if non mi torna, perchè non metterlo direttamente dentro il doOnNext precedente, magari usando switchIfEmpty?

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +        super.handleMessage(entity, paperRequest); // invio dato su delivery-push, che ci sia stato arricchimento o meno
questo va agganciato alla catena di funzioni webflux

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +        return eventDematDAO.findAllByRequestId(DEMAT_PREFIX + DELIMITER + paperRequest.getRequestId())
e anche questo va agganciato alla stessa catena di invocazioni.

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +        return eventDematDAO.findAllByRequestId(DEMAT_PREFIX + DELIMITER + paperRequest.getRequestId())
Concettualmente, devi avere un metodo che, salvo attività semplici (come un log ad esempio), inizia con return e poi una luuuuuuuuunga sequenza di then-map-doOnNext-flatMap-qualsiasiAltroComandoDelPifferoDiWebflux

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/AggregatorMessageHandler.java
> +        AtomicBoolean missingMeta = new AtomicBoolean(true);
questo non serve, vedi sotto

2023-03-14 15:54 UTC, fabriziolana commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/DirectlySendMessageHandler.java
> +        super.handleMessage(entity, paperRequest); // invio diretto dato su delivery-push
questo deve fare return super.handleMessage(..........).

Detto questo, visto che chiama solo il super, serve sta classe?o è una bozza che andrà aggiornata?

2023-03-14 16:07 UTC, FeliceMente commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/handler/DirectlySendMessageHandler.java
> +        super.handleMessage(entity, paperRequest); // invio diretto dato su delivery-push
ho tolto il metodo che si limita a chiamare super. La classe serve perché eredita una classe abstract

2023-03-15 11:34 UTC, fabriziolana approved these changes

2023-03-15 13:31 UTC, merged