feature/PN-5951
pagopa/pn-paper-channel pull request #289
Opened 2023-05-22 15:39 UTC by FeliceMente

2023-05-23 09:56 UTC, vincenzo-racca-pa requested changes

2023-05-23 09:56 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/paperchannel/mapper/SendEventMapper.java
> +import java.time.OffsetDateTime;
possiamo revertare questa classe? (vedo come ultima modifica solo l'aggiunta dei 2 package)

2023-05-23 09:56 UTC, vincenzo-racca-pa commented on src/main/java/it/pagopa/pn/paperchannel/middleware/queue/model/PNAG012Wrapper.java
> +        return new PNAG012Wrapper(originalPnDeliveryRequest, originalPaperRequest, statusDateTimeToSet);
Possiamo specificare tramite Javadoc questa data cosa sarebbe? (tramite nome variabile ho capito che non è facile perché può assumere diversi valori adesso)

2023-05-23 10:26 UTC, vincenzo-racca-pa submitted a review, later dismissed

2023-05-26 10:36 UTC, federicofatica-pagopa approved these changes

2023-05-26 10:37 UTC, merged