Bug/pn 5283
pagopa/pn-paper-channel pull request #295
Opened 2023-05-26 16:34 UTC by elenaibbaacn

2023-05-26 17:11 UTC, federicofatica-pagopa requested changes

2023-05-26 17:11 UTC, federicofatica-pagopa commented on src/test/java/it/pagopa/pn/paperchannel/service/QueueListenerServiceImplTest.java
> +//    @Test
Test da riabilitare

2023-05-26 17:11 UTC, federicofatica-pagopa commented on src/test/java/it/pagopa/pn/paperchannel/service/tenders/FileDownloadAndUploadFromServiceTest.java
> +//    @Test
Test da riabilitare

2023-05-26 17:11 UTC, federicofatica-pagopa commented on src/test/java/it/pagopa/pn/paperchannel/middleware/queue/consumer/QueueListenerTest.java
> +//    @Test
Test da riabilitare

2023-05-29 17:11 UTC, ariannazafarana commented
Procedo alla chiusura della PR poichè contiene delle commit non legate alla PN-5283

2023-05-29 17:11 UTC, closed without merging