Bug/pn 6962
pagopa/pn-paper-channel pull request #318
Opened 2023-06-26 09:28 UTC by CaicoOliviero

2023-06-27 12:03 UTC, federicofatica-pagopa requested changes

2023-06-27 12:44 UTC, CaicoOliviero commented on src/main/java/it/pagopa/pn/paperchannel/job/CloudWatchMetricJob.java
> +    private static final String NAMESPACE_CW_SELC = "selc-" + UUID_FOR_CLOUDWATCH_METRIC;
E' stata rimossa la costante **NAMESPACE_CW_SELC** in quanto non utilizata.

2023-06-27 12:44 UTC, CaicoOliviero commented on src/main/java/it/pagopa/pn/paperchannel/job/CloudWatchMetricJob.java
> +    private static final UUID UUID_FOR_CLOUDWATCH_METRIC = UUID.randomUUID();
La costante in questione è necessaria a generare un valore random da assegnare in aggiunta alla costante **NAMESPACE_CW_PDV**.

2023-06-28 08:48 UTC, CaicoOliviero commented on scripts/aws/cfn/microservice.yml
> +        ContainerEnvEntry48: !Sub 'PN_PAPERCHANNEL_CLOUDWATCHMETRICCRON=${CloudwatchMetricCron}'
sono state aggiunti i permessi per inviare le metriche a CloudWatch

2023-06-28 08:49 UTC, CaicoOliviero commented on src/main/java/it/pagopa/pn/paperchannel/job/CloudWatchMetricJob.java
> +        createAndSendMetric( NAMESPACE_CW_PDV, "PDVNumberOfWaitingRequests");
PDVNumberOfWaitingRequests è stata cambiata in PNPaperErrorRequest

2023-06-28 08:49 UTC, CaicoOliviero commented on src/main/java/it/pagopa/pn/paperchannel/job/CloudWatchMetricJob.java
> +    private static final UUID UUID_FOR_CLOUDWATCH_METRIC = UUID.randomUUID();
Lo UUID è stato rimosso.

2023-06-29 08:08 UTC, federicofatica-pagopa approved these changes

2023-06-29 08:09 UTC, vincenzo-racca-pa approved these changes

2023-06-29 09:31 UTC, merged