PN-9655: fix ordered attachments
pagopa/pn-paper-channel pull request #495
Opened 2024-05-28 07:28 UTC by AnaNiagu

2024-05-28 08:15 UTC, fabriziolana approved these changes

2024-05-28 14:30 UTC, vincenzo-racca-pa requested changes

2024-05-28 15:04 UTC, AnaNiagu commented on src/main/java/it/pagopa/pn/paperchannel/service/impl/PrepareAsyncServiceImpl.java
> -                .sequential()
@vincenzo-racca-pa Il .sequential() era legato al .parallel() che ho rimosso. Per il secondo flatMap l'ho appena sostituito in flatMapSequential() e di conseguenza modificato anche il test aggiungendo il delay che mancava

2024-06-06 14:12 UTC, vincenzo-racca-pa approved these changes

2024-06-07 08:26 UTC, fabriziolana approved these changes

2024-07-30 16:18 UTC, closed without merging